name: php-8.2-laravel-octane-franken

on:
  workflow_dispatch:

jobs:
  call-build-docker:
    uses: ./.github/workflows/docker-image.yml
    with:
      dockerfile_path: php/8.2-laravel-octane-franken.Dockerfile
      image: haidarns/php:8.2-laravel-octane-franken
      build_args: --rm --no-cache
      build_env: DOCKER_BUILDKIT=1
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
