name: Docker Image CI

on:
  workflow_call:  &inputs_common
    inputs:
      dockerfile_path:
        description: Dockerfile path
        required: true
        default: php/8.2-laravel.Dockerfile
        type: string
      image:
        description: Image name
        required: true
        default: haidarns/php:8.2-laravel-nginx
        type: string
      build_args:
        description: Additional docker build args
        default: --rm --no-cache
        type: string
      build_env:
        description: Docker build environment
        default: DOCKER_BUILDKIT=1
        type: string
  workflow_dispatch: *inputs_common

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ${{ inputs.build_env }} docker build --file ${{ inputs.dockerfile_path }} --tag ${{ inputs.image }} ${{ inputs.build_args }} .
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push docker image
      run: docker push ${{ inputs.image }}

